/**
 * Copyright (c) 2023-2024 Mxz Co., Ltd.
 *
 * @file Constants.ets
 * @project Lego
 * @author gemini
 * @crateTime 2024-01-30
 * @desc
 */

// system


export class Constants {
  /**
   * 100 percent
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * Default status height
   */
  static readonly DEFAULT_STATUS_HEIGHT: number = 32;

  /**
   * Default navigation height
   */
  static readonly DEFAULT_NAVI_HEIGHT: number = 56;
}